Project/app/controllers/debug.py
from flask import Blueprint, redirect, url_for, request, render_template, flash
from flask_login import login_required, current_user
from random import randint, choice
import datetime
import html

import config as Config
from app.utils import json_handler as JSON
from app.classes.survey import Survey
from app.classes.surveyQuestion import SurveyQuestion, QuestionType
from app.classes.surveyQuestionMCQ import SurveyQuestionMCQ
from app.classes.surveyQuestionTXT import SurveyQuestionTXT

from app.classes.question import Question
from app.classes.course import Course
from app.classes.offering import Offering
from app.classes.option import Option
from app.classes.response import Response
from app import db as DB

debug_blueprint = Blueprint('debug', __name__)

# Place to store random survey source
dictionary = {}

""" Taken from https://stackoverflow.com/questions/553303/generate-a-random-date-between-two-other-dates/8170651#8170651 """
def random_date(start, end):
    """Generate a random datetime between `start` and `end`"""
    return start + datetime.timedelta(
        # Get a random amount of seconds between `start` and `end`
        seconds=randint(0, int((end - start).total_seconds())),
    )

@debug_blueprint.route('/debug/', methods=['GET', 'POST'])
def debug():
    if not Config.debug_features:
        flash(u'Restart server with flag "-df" for feature', 'error')
        return redirect(request.referrer) if request.referrer else redirect(index.index)

    if request.method == "POST":
        # Sample surveys from https://opentdb.com/api.php?amount=50
        global dictionary
        # Ensures that long load only occurs when needed, once during
        # server life
        if not dictionary:
            dictionary = JSON.load_object('rand_survey_src')

        # Processes requests to generate DB objects
        if 's-lo' in request.form:
            try:
                s_lo = round(float(request.form.get("s-lo")))
                s_hi = round(float(request.form.get("s-hi")))
                q_lo = round(float(request.form.get("q-lo")))
                q_hi = round(float(request.form.get("q-hi")))
                r_lo = round(float(request.form.get("r-lo")))
                r_hi = round(float(request.form.get("r-hi")))
            except ValueError:
                flash(u'Parameters to generate invalid', 'error')
                return render_template('debug.html', surveys=Survey.query.all(), questions=Question.query.all())

            if dictionary:
                # Whether or not to delete existing surveys
                overwrite = request.form.get("overwrite")
                if overwrite:
                    Survey.query.delete()
                    SurveyQuestion.query.delete()
                    SurveyQuestionMCQ.query.delete()
                    SurveyQuestionTXT.query.delete()
                    Option.query.delete()
                    Response.query.delete()
                    DB.session.commit()

                courses_valid = {}
                for course in Course.query.all():
                    # Assumes true, course has no surveys
                    offerings_valid = []
                    for offering in course.offerings.all():
                        if offering.get_surveys():
                            continue
                        else:
                            offerings_valid.append(offering)
                    if offerings_valid:
                        courses_valid[course.name] = offerings_valid

                if not courses_valid:
                    flash('All offerings already have surveys', 'error')
                    return render_template('debug.html', surveys=Survey.query.all(), questions=Question.query.all())
                s_generated = 0
                courses = Course.query.all()
                max_num_s = randint(s_lo,s_hi)
                if max_num_s > len(Offering.query.all()):
                    max_num_s = len(Offering.query.all())
                if max_num_s  <= 1:
                    flash('All offerings already have surveys', 'error')
                    return render_template('debug.html', surveys=Survey.query.all(), questions=Question.query.all())
                s_to_gen = range(0,max_num_s)

                old_percentage = -1
                percentage = 0
                total = len(s_to_gen)
                for s_index in s_to_gen:
                    percentage = round(s_generated/total*100)
                    if percentage != old_percentage:
                        print(str(percentage) + "%                 ", end='\r')
                    s_generated += 1

                    title = html.unescape(dictionary[randint(0,len(dictionary)-1)]['question'])
                    if len(courses_valid.keys()) <= 0:
                        break
                    course = list(courses_valid.keys())[randint(0,len(courses_valid.keys())-1)]
                    offerings = courses_valid[course]
                    offering = offerings[randint(0,len(offerings)-1)]
                    courses_valid[course].remove(offering)
                    if len(offerings) == 0:
                        del courses_valid[course]

                    now = datetime.datetime.now()
                    start_date = now
                    end_date = random_date(now, now + datetime.timedelta(days=2))
                    dice = randint(0,2)
                    if dice == 2:
                        survey_phase = 'closed'
                    elif dice == 1:
                        survey_phase = 'open'
                    else:
                        survey_phase = 'review'
                    try:
                        survey = Survey(title, survey_phase, start_date, end_date, offering.id)
                    except:
                        s_generated -= 1
                        total -= 1
                        continue

                    for q_index in range(0,randint(q_lo,q_hi)):
                        d_index = randint(0,len(dictionary)-1)
                        if randint(0,1) == 1:
                            survey_question = SurveyQuestionMCQ(html.unescape(dictionary[d_index]['question']), q_index, True if randint(0,1) == 1 else False, survey.id)
                        else:
                            survey_question = SurveyQuestionTXT(html.unescape(dictionary[d_index]['question']), q_index, True if randint(0,1) == 1 else False, survey.id)

                        if survey_question.type == QuestionType.MCQ:
                            survey_question.options.append(Option(html.unescape(dictionary[d_index]['correct_answer']), survey.id))
                            for option in dictionary[d_index]['incorrect_answers']:
                                survey_question.options.append(Option(html.unescape(option), survey.id))
                        survey.questions.append(survey_question)

                        # Does random responses if it's generated as closed
                        if survey.phase == 'closed':
                            possible_responses = dictionary[d_index]['incorrect_answers']
                            possible_responses.append(dictionary[d_index]['correct_answer'])
                            # Doubles chance of correct answer being the response
                            possible_responses.append(dictionary[d_index]['correct_answer'])
                            for r_index in range(0,randint(r_lo,r_hi)):
                                survey_question.responses.append(Response(possible_responses[randint(0,len(possible_responses)-1)], survey_question.id))
                    offering.surveys.append(survey)

                    # DB.session.add(survey)
                DB.session.commit()
                flash(str(s_generated) + u' surveys generated', 'done')

        elif 'qp-lo' in request.form:
            qp_lo = round(float(request.form.get("qp-lo")))
            qp_hi = round(float(request.form.get("qp-hi")))

            overwrite = request.form.get("overwrite")
            if overwrite:
                Question.query.delete()
                DB.session.commit()

            if dictionary:
                q_generated = 0
                q_to_gen = range(0,randint(qp_lo,qp_hi))
                total = len(q_to_gen)
                for q_index in q_to_gen:
                    print(str(q_generated/total*100) + "%                 ", end='\r')
                    q_generated += 1
                    try:
                        DB.session.add(Question(html.unescape(dictionary[randint(0,len(dictionary)-1)]['question']), True if randint(0,1) == 1 else False))
                    except:
                        q_generated -= 1
                        total -= 1
                        continue

                DB.session.commit()
                flash(str(q_generated) + u' questions generated', 'done')

        elif 'reset-db' in request.form:
            DB.drop_all()
            DB.create_all()
            DB.load_defaults()
            DB.session.commit()
            flash(u'Database reset', 'done')            

        else:
            flash(u'Unknown command', 'error')

    return render_template('debug.html', surveys=Survey.query.all(), questions=Question.query.all())


# # Test surveys (THIS USES A DIFFERENT METHOD TO ONE ABOVE)
# # Note: this deletes existing surveys
# DB.surveys = {}
# DB.survey_lookup = {}
# from random import randint, choice
# dictionary = DB.load_object('webster_dictionary')
# for s_index in range(0,100):
#     survey = DB.Survey()

#     survey.title = str(dictionary[choice(list(dictionary.keys()))])[:100]
#     # survey.title = DB.gen_id()
#     survey.course = DB.courses[randint(0,len(DB.courses)-1)]
#     survey.offering = DB.offerings[survey.course][randint(0,len(DB.offerings[survey.course])-1)]
#     for q_index in range(0,randint(1,9)):
#         question = DB.Question(q_index)

Project/app/controllers/history.py
from flask import Blueprint, redirect, url_for, request, render_template
from flask_login import login_required, current_user

history_blueprint = Blueprint('history', __name__)

@history_blueprint.route('/history/')
@login_required
def history():
	return render_template('history.html', past_logins=[])

Project/app/controllers/lookup.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_required, login_user, logout_user, current_user
import time

import config as Config

from app.classes.user import User
from app.classes.enrolment import Enrolment
from app.classes.offering import Offering

lookup_blueprint = Blueprint('lookup', __name__)

lookup_obj = {}

# Set the route and accepted methods
@lookup_blueprint.route('/lookup/', methods=['GET', 'POST'])
def lookup():
    global lookup_obj
    if not Config.debug_features:
        flash(u'Restart server with flag "-df" for feature', 'error')
        return redirect(request.referrer) if request.referrer else redirect(index.index)
    
    t0 = time.time()

    # Avoids recreating lookup object every single time
    if not lookup_obj:
        lookup_obj = {}
        all_offerings = Offering.query.all()
        offerings = []
        for offering in all_offerings:
            query = str(offering.course_name) + ' ' + str(offering.semester)
            # If the enrolment's not in the lookup_obj, create list
            if query not in lookup_obj:
                lookup_obj[query] = []
            # For every enrolment in that course, adds it to the list
            for enrolment in offering.enrolments:
                user = User.query.get(enrolment.user_id)
                if user:
                    lookup_obj[query].append({'name':user.name, 'id':user.id, 'password':user.password, 'url':url_for("login.login", zid=user.id, password=user.password)})
            if not lookup_obj[query]:
                del lookup_obj[query]

    dt = time.time() - t0
    if(dt > 1):
        print(' * Time to generate lookup: ' + str(dt))
    return render_template('lookup.html', lookup=lookup_obj)

Project/app/controllers/metrics.py
from flask import Blueprint, redirect, url_for, request, render_template
from flask_login import login_required, current_user

from app import db as DB
from app.classes.survey import Survey
from app.classes.course import Course
from app.classes.enrolment import Enrolment
from app.classes.offering import Offering

metrics_blueprint = Blueprint('metrics', __name__)

# Displays list of surveys
@metrics_blueprint.route('/metrics/', methods=['GET', 'POST'])
@login_required
def metrics():
    if request.method == "POST":
        if 'survey-to-delete' in request.form:
            to_delete = request.form.get("survey-to-delete")
            survey = Survey.query.filter(Survey.id == to_delete).first()
            if survey:
                try:
                    offering = Offering.query.filter_by(id = survey.offering_id).first()
                    offering.delete_survey(survey.id)
                except:
                    pass
        elif 'survey-to-respond' in request.form:
            to_respond = request.form.get("survey-to-respond")

    # get all the courses the user is enrolled in 
    enrolment_ids = list(set(enrolment.offering_id for enrolment in current_user.enrolments))
    offerings = current_user.enrolled_offerings
    offerings_names = list(offering.course_name for offering in offerings)
    courses = current_user.enrolled_courses

    return render_template('metrics.html', courses=courses, enrolment=enrolment_ids, surveys=Survey.query.all())

Project/app/controllers/questions.py
from flask import Blueprint, redirect, url_for, request, render_template, flash
from flask_login import login_required, current_user
import uuid

from app import db as DB
from app.classes.question import Question

questions_blueprint = Blueprint('questions', __name__)

mandatory_options = {True:'Mandatory', False:'Optional'}

@questions_blueprint.route('/questions/', methods=['GET', 'POST'])
@login_required
def questions():
    if not current_user.admin:
        flash(u"Admin access only", 'error')
        return redirect(url_for('index.index'))
    if request.method == "POST":
        question_pool = Question.query.all()
        if 'question-to-delete' in request.form:
            to_delete = request.form.get("question-to-delete")
            question = Question.query.filter(Question.id == to_delete).first()
            if question:
                question.remove_question()
        elif 'question-to-add' in request.form:
            to_add = request.form.get("question-to-add")
            question_mandatory = request.form.get("question_mandatory")
            question = Question(to_add, question_mandatory == "True")
            try:
                question.add_question()
            except:
                pass
        elif 'add-option' in request.form:
            pass
    return render_template('questions.html', questions=Question.query.all(), mandatory_options=mandatory_options)

Project/app/controllers/survey_manage.py
from flask import Blueprint, redirect, url_for, request, render_template, flash
from flask_login import login_required, current_user

from app import db as DB
from app.classes.survey import Survey
from app.classes.course import Course
from app.classes.offering import Offering
from app.classes.surveyQuestionMCQ import SurveyQuestionMCQ

survey_manage_blueprint = Blueprint('survey_manage', __name__)

# Displays list of surveys
@survey_manage_blueprint.route('/survey/manage/', methods=['GET', 'POST'])
@login_required
def survey_manage():    
    if not current_user.admin:
        flash(u"Admin access only", 'error')
        return redirect(url_for('index.index'))

    return redirect(url_for('index.index'))

    if request.method == "POST":
        if 'survey-to-delete' in request.form:
            to_delete = request.form.get("survey-to-delete")
            survey = Survey.query.filter(Survey.id == to_delete).first()
            if survey:
                for completion in survey.completions:
                    DB.session.delete(completion)
                for question in survey.questions:
                    if isinstance(question, SurveyQuestionMCQ):
                        for option in question.options:
                            DB.session.delete(option)
                    for response in question.responses:
                        DB.session.delete(response)
                    DB.session.delete(question)
                DB.session.delete(survey)
                DB.session.commit()
        elif 'survey-to-respond' in request.form:
            to_respond = request.form.get("survey-to-respond")
        elif 'survey-permissions' in request.form:
            to_toggle = request.form.get("survey-permissions")
            survey = Survey.query.filter(Survey.id == to_toggle).first()
            if survey is not None:
                if survey.phase == "open":
                    survey.close_survey()
                    message_str = "closed"
                else:
                    survey.open_survey()
                    message_str = "opened"
                flash(u'Survey successfully ' + message_str, 'done')
                DB.session.commit()

    return render_template('survey-manage.html', courses=Course.query.all(), surveys=Survey.query.all())
    

Project/app/templates/dashboard-staff.html
<!doctype html>
<html>
  <head>
  <title>Dashboard</title>
  {% include "head.html" %}
  <style>
    .collection {
      overflow: visible;
    }
    .collapsible .collapsible {
      margin: 0;
    }
    .collapsible-header.active i {
      -ms-transform: rotate(180deg); /* IE 9 */
      -webkit-transform: rotate(180deg); /* Chrome, Safari, Opera */
      transform: rotate(180deg);
    }
    .course { 
      -moz-transition: all .2s ease-in;
      -o-transition: all .2s ease-in;
      -webkit-transition: all .2s ease-in;
      transition: all .2s ease-in;
      padding: 20px;
    }
    .course.active {
      background: #eee;
    }
  </style>
  </head>
  <body>

    {% include "header.html" %}

    <main>
      <div class="container">
        <h1 class="page-title"> Dashboard </h1>       
        <a href="{{ url_for('metrics.metrics') }}" class="waves-effect waves-light btn">Survey Results</a>

        {% for heading, section in sections %}
        <p><div class="divider"></div></p>
        <div class="section">
          <h2> {{heading}} </h2>
          <ul class="collapsible popout" data-collapsible="accordion">
            {% if section %}
            {% for course, offerings in section|dictsort %}
            <li>
              <div class="collapsible-header{%if loop.index==1%} active{%endif%} course " id="{{course}}">{{ course }}</div>
              {% if offerings %}
              {% for offering, surveys in offerings|dictsort %}
                <div class="collapsible-body no-padding">
                  <ul class="collapsible z-depth-0" data-collapsible="accordion" style="border: none;">
                    <li>
                      <div class="collapsible-header" id="{{course}}{{offering}}" style="border: none;">
                        <i class="material-icons">expand_more</i>
                        {{ offering }}
                      </div>
                      <div class="collapsible-body no-padding" style="border: none;">
                        {% if surveys %}
                        {% for survey in surveys %}
                          <ul class="collection">
                            <a href="{%if heading=='Review surveys'%}{{url_for('survey_review.survey_review', course=survey.offering.course_name, offering=survey.offering.semester, id=survey.id)}}{%elif heading=='Open surveys'%}{{url_for('survey_respond.survey_respond', id=survey.id)}}{%elif heading=='Closed surveys'%}{{url_for('survey_metrics.survey_metrics', course=survey.offering.course_name, offering=survey.offering.semester, id=survey.id)}}{%endif%}" class="collection-item">
                              <div class="row" style="margin-bottom: 0px;">
                                <div class="col s10" style="text-overflow: ellipsis; white-space: nowrap; overflow: hidden;">
                                  {{ survey.title }}
                                </div>
                                <div class="col s2">
                                  <i class="material-icons dropdown-button right" data-activates="dropdown-{{survey.id}}" data-beloworigin="false">more_vert</i>
                                </div>
                              </div>
                            </a>
                          </ul>
                        {% endfor %}
                        {% else %}
                          <ul class="collection">
                            <a href="{{url_for('survey_setup.survey_setup')}}" class="collection-item">Add new survey</a>
                          </ul>
                        {% endif %}
                      </div>
                    </li>
                  </ul>
                </div>
              {% endfor %}
              {% else %}
                <div class="collapsible-body no-padding">
                  <ul class="collapsible z-depth-0" data-collapsible="accordion" style="border: none;">
                    <li>
                      <div class="collapsible-header" id="{{course}}" style="border: none;">
                        <i class="material-icons">expand_more</i>
                        No surveys available
                      </div>
                      <div class="collapsible-body no-padding" style="border: none;">
                      </div>
                    </li>
                  </ul>
                </div>
              {% endif %}
            </li>
          {% endfor %}
          {% else %}
            <h5>No surveys to {%if current_user.staff%}review{%else%}answer{%endif%}</h5>
          {% endif %}
        </ul>
        {% endfor %}

        </div>
      </div>
    </main>
    <p>
    {% include "footer.html" %}
  </body>
</html>

  

Project/app/templates/footer.html
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l4 offset-l2 s6">
        <h5 class="white-text">Contributors</h5>
        <ul id="contributors">
          <p class="grey-text text-lighten-3">Jeremy Fu</p>
          <p class="grey-text text-lighten-3">Thomas Little</p>
          <p class="grey-text text-lighten-3">Randy Tjang</p>
          <p class="grey-text text-lighten-3">Jingshi Yang</p>
        </ul>
        <script>
          var ul = document.getElementById('contributors');
          for (var i = ul.children.length; i >= 0; i--) {
              ul.appendChild(ul.children[Math.random() * i | 0]);
          }
        </script>
      </div>
      <div class="col l4 offset-l2 s6">
        <h5 class="white-text">Attributions</h5>
        <ul>
          <p><a href="http://materializecss.com/" class="grey-text text-lighten-3">Materialize CSS</a></p>
          <p><a href="http://www.chartjs.org/" class="grey-text text-lighten-3">Chart.js</a></p>
          <a href="https://supraniti.github.io/Lean-Mean-Drag-and-Drop/" class="grey-text text-lighten-3">Lean Mean Drag and Drop</a></p>
          <a href="https://refreshless.com/nouislider/" class="grey-text text-lighten-3">noUiSlider</a></p>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © {{ now.year }} Copyright
    </div>
  </div>
</footer>

Project/app/templates/lookup-modal.html
<!-- Modal Structure -->
<div id="lookup" class="modal bottom-sheet" style="width: 85%; height: 50vw; margin: auto;">
  <div class="progress" id="lookup_loader" style="z-index: 1000; position: absolute;">
    <div class="indeterminate"></div>
  </div>
  <div class="modal-content" style="padding: 0px; height: 100%; width: 85%; margin: auto;">
    <iframe id="lookup_iframe" width="100%" height="100%" frameborder="0"></iframe>
  </div>
</div>
<script>
  $(document).ready(function() {
    // the "href" attribute of the modal trigger must specify the modal ID that wants to be triggered
    $('.modal').modal({

    });

    // $('.modal').modal({
    //     dismissible: true, // Modal can be dismissed by clicking outside of the modal
    //     opacity: .5, // Opacity of modal background
    //     inDuration: 300, // Transition in duration
    //     outDuration: 200, // Transition out duration
    //     startingTop: '4%', // Starting top style attribute
    //     endingTop: '10%', // Ending top style attribute
    //     ready: function(modal, trigger) { // Callback for Modal open. Modal and trigger parameters available.
    //       alert("Ready");
    //       console.log(modal, trigger);
    //     },
    //     complete: function() { alert('Closed'); } // Callback for Modal close
    //   }
    // );

    $('#lookup_iframe').on('load', function() {
      $('#lookup_loader').css("visibility", "hidden");
      $('#lookup_iframe').css("visibility", "visible");
    });
  });

  $("#lookup_btn").click(function() {
    if(!$('#lookup_iframe').attr('src')) {
      $('iframe#lookup_iframe').attr('src', '{{url_for('lookup.lookup')}}');
    }
  });
</script>

Project/app/templates/nav-admin.html
<ul id="slide-out" class="side-nav">
  <li><div class="user-view" style="text-shadow: 0px 1px 1px #000,0px 0px 5px #000;">
    <div class="background">
      <!-- <img src="{{ url_for('static',filename='img/banner-wide.jpg') }}" style="max-width:auto; height:100%;left:-30%;position: absolute;"> -->
      <img src="{{ url_for('static',filename='img/banner-sci.jpg') }}" style="max-height:auto; width:100%;left:-0%;position: absolute;">
    </div>
    <a href="#!user"><img class="circle" src="{{ url_for('static',filename='img/logo.jpg') }}"></a>
    <a href="#!name"><span class="white-text name">{{current_user.name}}</span></a>
    <a href="#!email"><span class="white-text email">{{current_user.id}}@unsw.edu.au</span></a>
  </div></li>

  <li><a class="waves-effect" href="{{ url_for('dashboard.dashboard') }}"><i class="material-icons">home</i>Home</a></li>
  <li><a class="waves-effect" href="{{ url_for('debug.debug') }}"><i class="material-icons">build</i>Debug</a></li>

  <li><div class="divider"></div></li>
  <li><a class="subheader">Surveys</a></li>
  <li><a class="waves-effect" href="{{ url_for('survey_setup.survey_setup') }}"><i class="material-icons">create</i>Survey creation</a></li>
  <li><a class="waves-effect" href="{{ url_for('survey_manage.survey_manage') }}"><i class="material-icons">dashboard</i>Survey management</a></li>
  <li><a class="waves-effect" href="{{ url_for('metrics.metrics') }}"><i class="material-icons">data_usage</i>Survey results</a></li>

  <li><div class="divider"></div></li>
  <li><a class="subheader">Questions</a></li>
  <li><a class="waves-effect" href="{{ url_for('questions.questions') }}"><i class="material-icons">comment</i>Question pool</a></li>

  <!-- Dropdown options -->
  <!-- <li class="no-padding">
    <ul class="collapsible collapsible-accordion">
      <li>
        <a class="collapsible-header">Dropdown<i class="material-icons">arrow_drop_down</i></a>
        <div class="collapsible-body">
          <ul>
            <li><a href="#!">First</a></li>
            <li><a href="#!">Second</a></li>
            <li><a href="#!">Third</a></li>
            <li><a href="#!">Fourth</a></li>
          </ul>
        </div>
      </li>
    </ul>
  </li> -->
</ul>
<!-- Navigation trigger -->
<a class='left waves-effect btn-flat button-collapse' data-activates="slide-out"><i class="material-icons">menu</i></a>  

Project/app/templates/nav-staff.html
<ul id="slide-out" class="side-nav">
  <li><div class="user-view" style="text-shadow: 0px 1px 1px #000,0px 0px 5px #000;">
    <div class="background">
      <!-- <img src="{{ url_for('static',filename='img/banner-wide.jpg') }}" style="max-width:auto; height:100%;left:-30%;position: absolute;"> -->
      <img src="{{ url_for('static',filename='img/banner-sci.jpg') }}" style="max-height:auto; width:100%;left:-0%;position: absolute;">
    </div>
    <a href="#!user"><img class="circle" src="{{ url_for('static',filename='img/logo.jpg') }}"></a>
    <a href="#!name"><span class="white-text name">{{current_user.name}}</span></a>
    <a href="#!email"><span class="white-text email">{{current_user.id}}@unsw.edu.au</span></a>
  </div></li>

  <li><a class="waves-effect" href="{{ url_for('dashboard.dashboard') }}"><i class="material-icons">home</i>Home</a></li>
  <li><a class="waves-effect" href="{{ url_for('debug.debug') }}"><i class="material-icons">build</i>Debug</a></li>

  <li><div class="divider"></div></li>
  <li><a class="subheader">Surveys</a></li>
  <li><a class="waves-effect" href="{{ url_for('metrics.metrics') }}"><i class="material-icons">data_usage</i>Survey results</a></li>

  <!-- Dropdown options -->
  <!-- <li class="no-padding">
    <ul class="collapsible collapsible-accordion">
      <li>
        <a class="collapsible-header">Dropdown<i class="material-icons">arrow_drop_down</i></a>
        <div class="collapsible-body">
          <ul>
            <li><a href="#!">First</a></li>
            <li><a href="#!">Second</a></li>
            <li><a href="#!">Third</a></li>
            <li><a href="#!">Fourth</a></li>
          </ul>
        </div>
      </li>
    </ul>
  </li> -->
</ul>
<!-- Navigation trigger -->
<a class='left waves-effect btn-flat button-collapse' data-activates="slide-out"><i class="material-icons">menu</i></a>  

Project/app/templates/nav-student.html
<ul id="slide-out" class="side-nav">
  <li><div class="user-view" style="text-shadow: 0px 1px 1px #000,0px 0px 5px #000;">
    <div class="background">
      <!-- <img src="{{ url_for('static',filename='img/banner-wide.jpg') }}" style="max-width:auto; height:100%;left:-30%;position: absolute;"> -->
      <img src="{{ url_for('static',filename='img/banner-sci.jpg') }}" style="max-height:auto; width:100%;left:-0%;position: absolute;">
    </div>
    <a href="#!user"><img class="circle" src="{{ url_for('static',filename='img/logo.jpg') }}"></a>
    <a href="#!name"><span class="white-text name">{{current_user.name}}</span></a>
    <a href="#!email"><span class="white-text email">{{current_user.id}}@unsw.edu.au</span></a>
  </div></li>

  <li><a class="waves-effect" href="{{ url_for('dashboard.dashboard') }}"><i class="material-icons">home</i>Home</a></li>
  <li><a class="waves-effect" href="{{ url_for('debug.debug') }}"><i class="material-icons">build</i>Debug</a></li>

  <li><div class="divider"></div></li>
  <li><a class="subheader">Surveys</a></li>
  <li><a class="waves-effect" href="{{ url_for('metrics.metrics') }}"><i class="material-icons">data_usage</i>Survey results</a></li>

  <!-- Dropdown options -->
  <!-- <li class="no-padding">
    <ul class="collapsible collapsible-accordion">
      <li>
        <a class="collapsible-header">Dropdown<i class="material-icons">arrow_drop_down</i></a>
        <div class="collapsible-body">
          <ul>
            <li><a href="#!">First</a></li>
            <li><a href="#!">Second</a></li>
            <li><a href="#!">Third</a></li>
            <li><a href="#!">Fourth</a></li>
          </ul>
        </div>
      </li>
    </ul>
  </li> -->
</ul>
<!-- Navigation trigger -->
<a class='left waves-effect btn-flat button-collapse' data-activates="slide-out"><i class="material-icons">menu</i></a>  